apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appointments-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: appointments-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: cloud-projet/appointments
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cloud-projet/appointments
        property: DB_PASSWORD
