apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: auth-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: cloud-projet/auth
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: cloud-projet/auth
        property: DB_PASSWORD
    - secretKey: AUTH_JWT_SECRET
      remoteRef:
        key: cloud-projet/auth
        property: AUTH_JWT_SECRET
