services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes_pwd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  appointments-service:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/notesdb
      DB_USER: notes
      DB_PASSWORD: notes_pwd
    ports:
      - "8080:8080"
    depends_on:
      - db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      AUTH_USERNAME: admin
      AUTH_PASSWORD: admin123
      AUTH_STATIC_TOKEN: medisante-token
    ports:
      - "8081:8081"

volumes:
  pgdata:
