apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-postgres-secret.yaml
  - 03-postgres-deployment.yaml
  - 04-postgres-service.yaml
  - 05-api-configmap.yaml
  - 06-api-secret.yaml
  - 07-api-deployment.yaml
  - 08-api-service.yaml
  - 09-auth-configmap.yaml
  - 10-auth-secret.yaml
  - 11-auth-deployment.yaml
  - 12-auth-service.yaml
  - 13-alb-ingress.yaml
